### ISSUE TITLE
[Client] props를 활용한 Todos 만들기

### ISSUE THREAD

**Issue by dddonnon** [jeon-seongjae/Team-Lvl-Todo#32]
## ISSUE
* Group: client
* Type: add
* Detail: React의 props를 활용해서 Todos 기능 만들기

## TODO
- [x] 리액트 서적 읽기
- [x] todo 추가 기능
- [x] todo 삭제 기능
- [x] todo 체크박스 토글 기능
- [x] todo 필터 기능

## Estimated time
> Pick one of the below
> 8h
